-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggDGjdh2W6ANRJL6c
6+DgL/KvOBaHXd4h4xQnD/CHx7KgCgYIKoZIzj0DAQehRANCAAR6o7UEgdgaM0co
GZHNeiIbRuQzC+vaCjSIoHyitNFLfQ1J/Dch/XQ/pRVHddwW3y43dRed6/H35WbC
mRCHDyMC
-----END PRIVATE KEY-----